services:
  app:
    build: .
    environment:
      HOST: "localhost"
      PORT: 8080
    ports:
      - 8080:8080
    depends_on:
      - database

  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "clean_architecture_db"
      MYSQL_USER: "mizu"
      MYSQL_PASSWORD: "root"
    ports:
      - 3306:3306
